default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: booklog_dev
  host: localhost
  port: 5432
  username: postgres
  password: password

test:
  <<: *default
  database: booklog_test
  host: localhost
  port: 5432
  username: postgres
  password: password

production:
  primary: &primary
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  queue:
    <<: *primary
  cable:
    <<: *primary
  cache:
    <<: *primary

