default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: booklog_dev

test:
  <<: *default
  database: booklog_test

production:
  <<: *default
  url: <%= ENV["dpg-d3jkfder433s739coue0-a.singapore-postgres.render.com"] %>
  database: shorty_8uir
  username: shorty
  password: odc3Doogq8yBAOoayppkwIuyKoEwfOyx


