default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: booklog_dev
  host: 127.0.0.1
  port: 4000
  username: root
  password:

test:
  <<: *default
  database: booklog_test
  host: 127.0.0.1
  port: 4000
  username: root
  password:

production:
  primary: &primary
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  queue:
    <<: *primary
  cable:
    <<: *primary
  cache:
    <<: *primary